import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/custom/header" // Adjust the path as needed
import Body from "@/components/custom/body";
import Hero from "@/components/custom/hero";
import Community from "@/components/custom/community";
import Unlock from "@/components/custom/unlock";
import Achievements from "@/components/custom/achievement";

const manrope = Manrope({ subsets: ["latin"], variable: '--font-manrope' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
        "min-h-screen bg-background font-manrope antialiased",
        manrope.variable
      )}>
        <Header />
        
        <Hero />

        <Body />

        <Community />

        <Unlock />

        <Achievements />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
